-- QUESTION
INSERT INTO `question` (`id`, `label`, `category`, `subcategory`, `points`, `correct_answer`, `incorrect_answer1`, `incorrect_answer2`, `incorrect_answer3`)
VALUES (1,'Did you open the door?','java','spring',1,'tension','Our past','important to remember','They sleep'),
    (2,'Do you think Tom will come?','java','spring',1,'engineering','Sue was','favorite classmate','The black'),
    (3,'How big an idiot do you think I am?','java','spring',1,'farmer','We long','day tomorrow','want chocolate'),
    (4,'Is football a sport?','java','spring',1,'virus','The train','leave at 8AM','real problem'),
    (5,'What is the deal with Tom?','java','spring',1,'contract','need stop','cleaned my room','No have'),
	(6,'If you could meet anyone, who would it be?','java','spring',1,'impression','Everybody','expecting bonus','Technology'),
	(7,'What do you want to do when you grow up?','java','spring',1,'dirt','makes us','our past','lovely day'),
	(8,'Have you spoken to him?','java','spring',1,'salad','have crush','Albert','apply online'),
	(9,'What was the big announcement?','java','spring',1,'procedure','This room','big enough','keeping me'),
	(10,'Why me?','java','spring',1,'bedroom','at night','His mom','slingshot'),
	(11,'Do you think you are a bigger man than him?','java','spring',1,'region','every day','been up','He goes'),
    (12,'Are you ready for your big date?','java','spring',1,'volume','play football','Talking pleasure','about him'),
    (13,'Do you deliver to this address?','java','spring',1,'chocolate','Get away','slimy','rice and beans'),
    (14,'Does she drink coffee?','java','spring',1,'conversation','like dinner','Dot worry','Corduroy'),
    (15,'What is new with you?','java','spring',1,'poet','double-denim','did understand','why anyone'),
	(16,'It is quite a big deal, is it not?','java','spring',1,'importance','little worm','He would','pay quarter'),
	(17,'Who wrote Treasure Island?','java','spring',1,'cancer','million dollars','degree in singing','what remember'),
	(18,'Where did you see him?','java','spring',1,'reaction','she was','at 8 pm','I planned'),
	(19,'Could I ask you to do me a big favor?','java','spring',1,'variation','walk home','but my','feet got'),
	(20,'Which is deeper, a lake or an ocean?','java','spring',1,'cheek','so sore','find bus','stop instead'),
	(21,'Have you opened the door?','java','hibernate',1,'tension','orange tree','her backyard','blown away'),
	(22,'What is wrong with my shirt?','java','hibernate',1,'engineering','the hurricane','She went','first date'),
	(23,'Would you say slowly, please?','java','hibernate',1,'farmer','boy before','she realized','Marxist'),
	(24,'What is your address?','java','hibernate',1,'virus','He says','he is you','from future'),
    (25,'Could this be the start of something big?','java','hibernate',1,'contract','come back','warn you','one thing'),
    (26,'What do you see?','java','hibernate',1,'impression','She promised','reserve room','She beaming'),
    (27,'Is he yours?','java','hibernate',1,'dirt','You look','so amazing','red dress'),
    (28,'That was a big surprise, was it not?','java','hibernate',1,'salad','and heels','The girl','was wearing'),
	(29,'What did he tell you?','java','hibernate',1,'procedure','denim jacket','denim shirt','denim jeans'),
	(30,'If you could meet anyone, who would it be?','java','hibernate',1,'bedroom','beautiful dress','left donuts','side of the road'),
	(31,'Did you say the plant turned purple?','java','hibernate',1,'region','Sit down','shut up','Criticizing'),
	(32,'Did you get that?','java','hibernate',1,'volume','racists','a repression','free speech'),
	(33,'What are you talking about?','java','hibernate',1,'chocolate','much work','He went','fast slide'),
	(34,'What is your favorite ice cream flavor?','java','hibernate',1,'conversation','bodyweight training','wanted Portland','go to the bookstores'),
    (35,'What is your favorite thing about school?','java','hibernate',1,'poet','Everyone goes','expensive gyms','likes to wear'),
	(36,'who will do all the housework?','java','hibernate',1,'importance','all-black outfits','you do tell','where he went'),
	(37,'What is that huge building in front of us?','java','hibernate',1,'cancer','I am going','start crying','only I fly'),
	(38,'Are you ready for your big day?','java','hibernate',1,'reaction','All the names','listed in','alphabetical order'),
	(39,'Where is the President right now?','java','hibernate',1,'variation','be silly','you going','the game'),
	(40,'Do you have any hidden talents?','java','hibernate',1,'cheek','This should','a big deal','Do not get'),
	(41,'What kind of music do you like to listen to?','java','jsp',1,'tension','too excited','Very good','good job'),
	(42,'Do you think this is too big?','java','jsp',1,'engineering','sweetheart','She hated','first dates'),
	(43,'May I come in?','java','jsp',1,'farmer','This is my','younger brother','Being fashionable'),
	(44,'Could you spell it?','java','jsp',1,'virus','is a lot','of work','You should'),
	(45,'What was the big announcement?','java','jsp',1,'contract','never lie','I did like','how they'),
	(46,'What is the matter?','java','jsp',1,'impression','dyed my hair','today at','the salon'),
	(47,'Are you all right?','java','jsp',1,'dirt','Her handbag','matches her','clothes perfectly'),
	(48,'How much did your lunch cost?','java','jsp',1,'salad','When we children','everything around us','looks so big'),
	(49,'Why dont we go dancing?','java','jsp',1,'procedure','Pluto','may not be','a planet'),
	(50,'Do you think Tom will come?','java','jsp',1,'bedroom','anymore but','a planet','in my heart'),
	(51,'We are just one big, happy family, are we not?','java','jsp',1,'region','She threw her','back out','He is not'),
	(52,'Does she live in Paris?','java','jsp',1,'volume','the problem','I am','Being fashionable'),
	(53,'What do you do for Valentines Day?','java','jsp',1,'chocolate','not expensive','You look','really sharp'),
	(54,'What is bothering you?','java','jsp',1,'conversation','today I do','not like','the polluted'),
    (55,'Do you guys have any big plans tonight?','java','jsp',1,'poet','atmosphere of','big cities','get paid'),
    (56,'Has he come to get you yet?','java','jsp',1,'importance','a lizard','Sarah found','her life'),
    (57,'What toy do you wish you had?','java','jsp',1,'cancer','for the rest','I like','go to school'),
    (58,'Just how big an idiot do you think I am?','java','jsp',1,'reaction','She wished','she could','asparagus'),
    (59,'What is your favorite color?','java','jsp',1,'variation','brussel sprouts','ship out','Do open'),
	(60,'Who do they believe you are?','java','servlet',1,'cheek','green thumb','the door','Good gracious'),
	(61,'May I have some water?','java','servlet',1,'tension','Shape up','Learning about','other countries'),
	(62,'Can you come over now?','java','servlet',1,'engineering','history is fun','She always','thought matcha'),
	(63,'Could you spell it?','java','servlet',1,'farmer','looked gross','unappetizing','We ate'),
	(64,'Have you got a match?','java','servlet',1,'virus','a big dinner','and then went','right to bed'),
	(65,'Is that it?','java','servlet',1,'contract','Nicky is','911 operator','My mom'),
	(66,'Why not?','java','servlet',1,'impression','madea','a carpenter','milkshake'),
	(67,'What do you want me to say?','java','servlet',1,'dirt','frozen bananas','chocolate sauce','She invested'),
	(68,'Do you think this is too big?','java','servlet',1,'salad','in Apple','right before','it got big'),
	(69,'Have you spoken to him?','java','servlet',1,'procedure','You did right','in me by','telling the truth'),
	(70,'How do you celebrate Easter?','java','servlet',1,'bedroom','It is clear','that he has','made a big'),
	(71,'Does he go to school?','java','servlet',1,'region','Big mistake','All the bikes','locked up'),
	(72,'Do you know that man with a big hat on?','java','servlet',1,'volume','outside the subway','stations','are missing'),
	(73,'Would you like to have some coffee?','java','servlet',1,'chocolate','either a wheel','or a seat','I wish you'),
	(74,'It was not a big store, right?','java','servlet',1,'conversation','would make','a list of','newly'),
    (75,'Can I open the door?','java','servlet',1,'poet','published','books','I prefer'),
    (76,'Do you like spaghetti?','java','servlet',1,'importance','ice cream','over cake','You have'),
    (77,'What did he tell you?','java','servlet',1,'cancer','some schoolwork','have fun','with you'),
    (78,'Are trees green or blue?','java','servlet',1,'reaction','They speak','English','United States'),
    (79,'Have you ever been late a day in your life?','java','servlet',1,'variation','I am happy','see you','today'),
    (80,'Could you tell me what time it is?','java','servlet',1,'cheek','The job','was bigger','than I'),
    (81,'Do you have a bigger one?','javascript','react',1,'tension','anticipated','Her fridge','very old'),
    (82,'What kind of music do you like to listen to?','javascript','react',1,'engineering','your act','act together','Good gracious'),
    (83,'What do you do for Thanksgiving?','javascript','react',1,'farmer','It could','possibly become','big problem'),
    (84,'What are you looking for?','javascript','react',1,'virus','The Grand','Grand Canyon','got snow'),
    (85,'Why did you come?','javascript','react',1,'contract','for the first','First time','in decades'),
    (86,'Do you have a bigger frying pan?','javascript','react',1,'impression','all tourists','very excited','The box'),
    (87,'Do you think you are a bigger man than him?','javascript','react',1,'dirt','wrapped','tiny silver','red glitter'),
	(88,'Do we know each other?','javascript','react',1,'salad','Geese','Wiggle fingers','go there'),
	(89,'Which is deeper, a lake or an ocean?','javascript','react',1,'procedure','takes school','Bumble better','That broke'),
	(90,'When did China become a Communist country?','javascript','react',1,'bedroom','watermelons','more careful','will have'),
	(91,'Is the door open?','javascript','react',1,'region','die hard','Old habits','Blue Mercury'),
	(92,'Did you say the plant turned purple?','javascript','react',1,'volume','was called','The spa','used work'),
	(93,'What are your favorite foods?','javascript','react',1,'chocolate','soon get','You will','my friends'),
	(94,'Am I in the White House?','javascript','react',1,'conversation','I love','about','we talk'),
	(95,'What does your room look like?','javascript','react',1,'poet','on what','I lost','called football'),
	(96,'Would you like to have some coffee?','javascript','react',1,'importance','should be','No sport','open spaces'),
	(97,'Has he come to get you yet?','javascript','react',1,'cancer','I like','so long','there for'),
    (98,'Could you spell it?','javascript','react',1,'reaction','to go','been trying','We have'),
    (99,'Where do you live?','javascript','react',1,'variation','feel lazy','make me','Naps'),
    (100,'Will you be free tomorrow evening?','javascript','react',1,'cheek','rocks are smooth','another one', 'transformers');